pipeline {
     agent any
    stages {
         stage('Pre cleanup'){ 
              echo 'One way or another, Im starting'
              cleanWs() 
         }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deploy.sh'
            }
            
        }
          
    }
       post {
            always { 
                 echo 'One way or another, I have finished'
               cleanWs()
            }
            unstable {
                    echo 'I am unstable :/'
            }
         }
}
